config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = 'Store Management'
admin.site.index_title = 'Website Management'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('accounts/', include('store.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('', include('store.pages.urls', namespace='pages')),
    path('products/', include('store.products.urls', namespace='products')),
    path('comments/', include('store.comments.urls', namespace='comments')),
    path('qas/', include('store.qas.urls', namespace='qas')),
    path('cart/', include('store.cart.urls', namespace='cart')),
    path('search/', include('store.search.urls', namespace='search')),
    path('shipping/', include('store.shipping.urls', namespace='shipping')),
    path('orders/', include('store.orders.urls', namespace='orders')),
    path('coupons/', include('store.coupons.urls', namespace='coupons')),
    path('payment/', include('store.payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='add'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove'),
    path('clear/', views.cart_clear, name='clear'),
]

store/coupons/urls.py
from django.urls import path

from . import views

app_name = 'coupons'

urlpatterns = [
    path('', views.apply_coupon, name='apply'),
]

store/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_create_view, name='create'),
    path('<uuid:order_id>/pdf/', views.order_pdf, name='order_pdf'),
    path('list/', views.CustomerOrderListView.as_view(), name='customer_list'),
]

store/cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label=_('quantity')
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput,
    )

store/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.utils.translation import gettext as _
from django.contrib import messages

from store.products.models import Product
from store.coupons.forms import CouponApplyForm
from .cart import Cart
from .forms import CartAddProductForm


def cart_detail(request):
    cart = Cart(request)

    for item in cart:
        item['product_update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'override': True
            }
        )

    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {
        'cart': cart, 
        'coupon_apply_form': coupon_apply_form,
    })


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product, cd['quantity'], cd['override'])

    return redirect('cart:detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def cart_clear(request):
    cart = Cart(request)

    if len(cart):
        cart.clear()
        messages.success(request, _('All products successfully removed from your cart'))
    else:
        messages.warning(request, _('Your cart is already empty.'))

    return redirect('cart:detail')

store/cart/templates/cart/detail.html
{% extends '_base.html' %}

{% load static %}
{% load product_tags %}
{% load humanize %}
{% load i18n %}

{% block custom_css %}
<link href="{% static 'css/cart.css' %}" rel="stylesheet">
{% endblock %}

{% block page_title %}
{% trans 'Cart' %}
{% endblock %}

{% block content %}
<main class="bg_gray">
	<div class="container margin_30">
		<div class="page_header">
			<h1>{% trans 'Cart page' %}</h1>
		</div>
		<!-- /page_header -->
		<table class="table table-striped cart-list">
			<thead>
				<tr>
					<th>
						{% trans 'Product' %}
					</th>
					<th>
						{% trans 'Price' %}
					</th>
					<th>
						{% trans 'Quantity' %}
					</th>
					<th>
						{% trans 'Subtotal' %}
					</th>
					<th>

					</th>
				</tr>
			</thead>
			<tbody>

				{% for item in cart %}
				<tr>
					<td>
						<div class="thumb_cart">
							<img data-src="{{ item.product_obj.main_cover.url }}" class="lazy"
								alt="Image">
						</div>
						<span class="item_cart">{{ item.product_obj.title }}</span>
					</td>
					<td>
						<strong>{% trans '$' %}{{ item.price|persian_number|intcomma:False }}</strong>
					</td>
					<td>

						<form action="{% url 'cart:add' item.product_obj.id %}" method="POST">
							{% csrf_token %}
							<div class="numbers-row">
								<input type="text" value="{{ item.quantity }}" id="quantity_1"
									class="qty2" name="quantity">
								{{ item.product_update_quantity_form.override }}
								<div class="inc button_inc">+</div><div class="dec button_inc">-</div>
							</div>
							<button type="submit" class="btn_1 gray">{% trans 'Update Cart' %}</button>
						</form>

					</td>
					<td>
						<strong>{% trans '$' %}{{ item.total_price|persian_number|intcomma:False }}</strong>
					</td>
					<td class="options">
						<a href="{% url 'cart:remove' item.product_obj.id %}"><i
								class="ti-trash"></i></a>
					</td>
				</tr>
				{% endfor %}

			</tbody>
		</table>

		<div class="row add_top_30 flex-sm-row-reverse cart_actions">
			<div class="col-sm-4 text-end">
				<a href="{% url 'cart:clear' %}" class="btn_1 gray">{% trans 'Clear Cart' %}</a>
			</div>
			<div class="col-sm-8">
				<form action="{% url 'coupons:apply' %}" method="POST">
					{% csrf_token %}

					<div class="apply-coupon">
						<div class="form-group">
							<div class="row g-2">
								<div class="col-md-6"><input type="text" name="code" value
										placeholder="{% trans 'Promo code' %}" class="form-control"></div>
								<div class="col-md-4"><button type="submit" class="btn_1 outline">{% trans 'Apply Coupon' %}</button></div>
							</div>
						</div>
					</div>

				</form>

			</div>
		</div>
		<!-- /cart_actions -->

	</div>
	<!-- /container -->

	<div class="box_cart">
		<div class="container">
			<div class="row justify-content-end">
				<div class="col-xl-4 col-lg-4 col-md-6">
					<ul>
						{% if cart.coupon %}
						<li>
							<span>{% trans 'Subtotal' %}</span> {% trans '$' %}{{ cart.get_total_price|persian_number|intcomma:False }}
						</li>
						<li>
							<span>
								{{ cart.coupon.code }} {% trans 'coupon' %} ({{ cart.coupon.discount }}% {% trans 'off' %})
							</span>
							- {% trans '$' %}{{ cart.get_discount|persian_number|intcomma:False }}
						</li>
						{% endif %}

						<li>
							<span>{% trans 'Total' %}</span> {% trans '$' %}{{ cart.get_total_price_after_discount|persian_number|intcomma:False }}
						</li>
					</ul>
					<a href="{% url 'shipping:create' %}" class="btn_1 full-width cart">{% trans 'Proceed to Checkout' %}</a>
				</div>
			</div>
		</div>
	</div>
	<!-- /box_cart -->

</main>
<!--/main-->
{% endblock %}