config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = 'Store Management'
admin.site.index_title = 'Website Management'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('accounts/', include('store.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('', include('store.pages.urls', namespace='pages')),
    path('products/', include('store.products.urls', namespace='products')),
    path('comments/', include('store.comments.urls', namespace='comments')),
    path('qas/', include('store.qas.urls', namespace='qas')),
    path('cart/', include('store.cart.urls', namespace='cart')),
    path('search/', include('store.search.urls', namespace='search')),
    path('shipping/', include('store.shipping.urls', namespace='shipping')),
    path('orders/', include('store.orders.urls', namespace='orders')),
    path('coupons/', include('store.coupons.urls', namespace='coupons')),
    path('payment/', include('store.payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_create_view, name='create'),
    path('<uuid:order_id>/pdf/', views.order_pdf, name='order_pdf'),
    path('list/', views.CustomerOrderListView.as_view(), name='customer_list'),
]

store/payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process_sandbox_view, name='process'),
    path('callback/', views.payment_callback_sandbox_view, name='callback'),
]

store/orders/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import Decimal
from uuid import uuid4
from django.utils.translation import gettext_lazy as _


class Order(models.Model):
    shipping = models.ForeignKey('shipping.Shipping', on_delete=models.PROTECT, verbose_name=_('shipping'))
    user = models.ForeignKey('accounts.Customer', on_delete=models.PROTECT, verbose_name=_('user'))
    order_number = models.UUIDField(_('order_number'), unique=True, default=uuid4, editable=False)
    note = models.CharField(_('note'), max_length=200, blank=True)
    is_paid = models.BooleanField(_('is_paid'), default=False)
    created = models.DateTimeField(_('created'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)
    coupon = models.ForeignKey(
        'coupons.Coupon', 
        on_delete=models.SET_NULL,
        related_name='orders',
        blank=True,
        null=True,
        verbose_name=_('coupon'))
    discount = models.IntegerField(_('discount'), default=0, validators=[
        MaxValueValidator(100),
        MinValueValidator(0)
    ])

    zarinpal_authority = models.CharField(_('zarinpal_authority'), max_length=255, blank=True)
    zarinpal_ref_id = models.CharField(_('zarinpal_ref_id'), max_length=255, blank=True)
    zarinpal_data = models.TextField(_('zarinpal_data'), blank=True)

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        return f'Order id={self.id} for {self.user.first_name}'

    def get_total_price_before_discount(self):
        return sum(item.quantity * item.price for item in self.items.all())

    def get_discount(self):
        total_price = self.get_total_price_before_discount()
        if self.discount:
            return round(total_price * (self.discount / Decimal(100)), 0)
        return Decimal(0)
    
    def get_total_price(self):
        total_price = self.get_total_price_before_discount()
        return round(total_price - self.get_discount(), 0)


class OrderItem(models.Model):
    order = models.ForeignKey('orders.Order', on_delete=models.PROTECT, related_name='items', verbose_name=_('order'))
    product = models.ForeignKey('products.Product', on_delete=models.PROTECT, related_name='order_items', verbose_name=_('product'))
    quantity = models.PositiveIntegerField(_('quantity'), default=1)
    price = models.PositiveIntegerField(_('price'))

    class Meta:
        verbose_name = _('Order Item')
        verbose_name_plural = _('Order Items' )

    def get_price(self):
        return self.price * self.quantity

store/orders/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('note',)

store/orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.conf import settings
from django.db import transaction
from django.db.models import F
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.translation import gettext as _

import weasyprint
import os

from store.cart.cart import Cart
from store.shipping.models import Shipping
from .forms import OrderForm
from .models import OrderItem, Order


@login_required
def order_create_view(request):
    cart = Cart(request)

    if len(cart) == 0:
        messages.warning(request, _('Your cart is empty please add product to cart.'))
        return redirect('products:list')

    shipping_id = request.session.get('shipping_id')

    shipping = get_object_or_404(Shipping, id=shipping_id)

    if request.method == 'POST':
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            with transaction.atomic():
                order_obj = order_form.save(commit=False)
                if cart.coupon:
                    order_obj.coupon = cart.coupon
                    order_obj.discount = cart.coupon.discount
                    del request.session['coupon_id']
                order_obj.user = request.user.customer
                order_obj.shipping = shipping
                order_obj.save()

                order_items = (
                    OrderItem(
                        order=order_obj,
                        product=cart_item['product_obj'],
                        quantity=cart_item['quantity'],
                        price=cart_item['price'],
                    )
                    for cart_item in cart
                )

                OrderItem.objects.bulk_create(order_items)

                cart.clear()

                request.user.first_name = shipping.address.receiver_first_name
                request.user.last_name = shipping.address.receiver_last_name
                request.user.save()

                request.session['order_id'] = order_obj.id

                del request.session['shipping_id']

                messages.success(request, _('Order successfully created.'))

                return redirect('payment:process')

    else:
        order_form = OrderForm()

    return render(request, 'orders/create.html', {
        'shipping': shipping,
        'order_form': order_form,
    })


def order_pdf(request, order_id):
    order = get_object_or_404(Order, order_number=order_id)
    html = render_to_string('orders/pdf.html', {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response, stylesheets=[
        weasyprint.CSS(os.path.join(settings.STATICFILES_DIRS[0], 'css\pdf.css'))
    ])
    return response


class CustomerOrderListView(LoginRequiredMixin, generic.ListView):
    template_name = 'orders/list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user.customer) \
            .select_related('shipping', 'user') \
            .prefetch_related('items') \
            .annotate(address=F('shipping__address__address')) \
            .order_by('-created')

store/orders/templates/orders/create.html
{% extends '_base.html' %}

{% load static %}
{% load product_tags %}
{% load humanize %}
{% load i18n %}

{% load jalali_tags %}

{% block custom_css %}
    <link href="{% static 'css/checkout.css' %}" rel="stylesheet">
{% endblock %}

{% block page_header %}
    {% trans 'Order Page' %}
{% endblock %}

{% block content %}
    <main class="bg_gray">
        <div class="container margin_30">
            <!-- /page_header -->
            <form action="" method="POST">
                {% csrf_token %}
                {% if order_form.errors %}
                    <div class="alert alert-danger">
                        {{ order_form.errors }}
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col-lg-4 col-md-6">
                        <div class="step first">
                            <h3>1. {% trans 'Order Note' %}</h3>
                            <div class="tab-content checkout">
                                <div class="tab-pane fade show active" id="tab_1" role="tabpanel"
                                     aria-labelledby="tab_1">
                                    <div class="form-group">
                                        <textarea type="text" class="form-control" placeholder="{% trans 'Note' %}"
                                                  name="notes"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /step -->

                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="step last">
                            <h3>2. {% trans 'Order Summary And Payment' %}</h3>
                            <div class="box_general summary">

                                <ul>
                                    {% for item in cart %}
                                        <li class="clearfix"><em>{{ item.quantity }}x {{ item.product_obj.title }}</em>
                                            <span>{% trans '$' %}{{ item.price|persian_number|intcomma:False }}</span></li>
                                    {% endfor %}
                                </ul>

                                {% if cart.coupon %}
                                    
                                    <ul>
                                        <li class="clearfix">
                                            <em><strong>{% trans 'Subtotal' %}</strong></em>
                                            <span>{% trans '$' %}{{ cart.get_total_price|persian_number|intcomma:False }}</span>
                                        </li>
                                        
                                        <li class="clearfix">
                                            <em><strong>
                                                "{{ cart.coupon.code }}" {% trans 'coupon' %}
						                        ({{ cart.coupon.discount }}% {% trans 'off' %})
                                            </strong></em>
                                            <span>- {% trans '$' %}{{ cart.get_discount|persian_number|intcomma:False }}</span>
                                        </li>
                                    </ul>

                                {% endif %}

                                <ul>
                                    <li class="clearfix"><em><strong>{% trans 'Delivery Date' %}</strong></em>
                                        <span>{{ shipping.delivery_date|to_jalali:'%Y/%m/%d' }} {% trans 'in' %} {{ shipping.delivery_time_slot }}</span></li>
                                    </ul>
                                    
                                <div class="total clearfix">{% trans 'TOTAL' %} <span>{% trans '$' %}{{ cart.get_total_price_after_discount|persian_number|intcomma:False }}</span></div>

                                    <input type="submit" class="btn_1 full-width" value="{% trans 'Payment' %}">
                                </div>
                                <!-- /box_general -->

                            </div>
                            <!-- /step -->
                        </div>
                    </div>
                    <!-- /row -->
                </form>
            </div>
            <!-- /container -->
        </main>
    <!--/main-->
{% endblock %}

store/orders/templates/orders/list.html
{% extends '_base.html' %}

{% load jalali_tags %}
{% load product_tags %}
{% load humanize %}
{% load i18n %}

{% block page_title %}
    {% trans 'Order List' %}
{% endblock %}

{% block content %}

    <div class="container-fluid">
        <div class="m-5">
            <table class="table table-bordered table-hover">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">{% trans 'Order ID' %}</th>
                    <th scope="col">{% trans 'Address' %}</th>
                    <th scope="col">{% trans 'Date' %}</th>
                    <th scope="col">{% trans 'discount' %}</th>
                    <th scope="col">{% trans 'Total Amount' %}</th>
                    <th scope="col">{% trans 'Status' %}</th>
                    <th scope="col">{% trans 'PDF' %}</th>

                </tr>
                </thead>
                <tbody>

                {% for order in orders %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ order.order_number }}</td>
                        <td>{{ order.address }}</td>
                        <td>{{ order.created|to_jalali:'%Y/%m/%d - %H:%S' }}</td>
                        <td>{{ order.discount }}%</td>
                        <td>{% trans '$' %}{{ order.get_total_price|persian_number|intcomma:False }}</td>
                        <td>
                            {% if order.is_paid == False %}
                            <i class="fa-regular fa-circle-xmark"></i>
                            <a href="{% url 'payment:process' %}">{% trans 'Pay' %}</a>
                            {% else %}
                            <i class="fa-solid fa-check"></i>
                            {% endif %}
                        </td>
                        <td>
                            {% if order.is_paid %}
                                <a href="{% url 'orders:order_pdf' order.order_number %}">{% trans 'Download' %}</a>
                            {% endif %}
                        </td>
                    </tr>

                {% endfor %}

                </tbody>
            </table>

        </div>
    </div>

{% endblock %}

store/orders/templates/orders/pdf.html
{% load i18n %}

<html>
    <body>
        <h1>{% trans 'My Shop' %}</h1>
        <p>
            {% trans 'Invoice no.' %} {{ order.id }}<br>
            <span class="secondary">
                {{ order.created|date:"M d, Y" }}
            </span>
        </p>
        <h3>{% trans 'Bill to' %}</h3>
        <p>
            {{ order.shipping.address.receiver_first_name }} {{ order.shipping.address.receiver_last_name }}<br>
            {{ order.shipping.address.address }}<br>
            {{ order.shipping.address.postal_code }}, {{ order.shipping.address.city }}
        </p>
        <h3>{% trans 'Items bought' %}</h3>
        <table>
            <thead>
                <tr>
                    <th>{% trans 'Product' %}</th>
                    <th>{% trans 'Price' %}</th>
                    <th>{% trans 'Quantity' %}</th>
                    <th>{% trans 'Cost' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for item in order.items.all %}
                <tr class="row{% cycle "1" "2" %}">
                    <td>{{ item.product.title }}</td>
                    <td class="num">{% trans '$' %}{{ item.price }}</td>
                    <td class="num">{{ item.quantity }}</td>
                    <td class="num">{% trans '$' %}{{ item.get_price }}</td>
                </tr>
                {% endfor %}

                {% if order.coupon %}
                <tr class="subtotal">
                    <td colspan="3">{% trans 'Subtotal' %}</td>
                    <td class="num">
                        {% trans '$' %}{{ order.get_total_price_before_discount }}
                    </td>
                </tr>
                <tr>
                    <td colspan="3">
                        "{{ order.coupon.code }}" {% trans 'coupon' %}
                        ({{ order.discount }}% {% trans 'off' %})
                    </td>
                    <td class="num neg">
                        - {% trans '$' %}{{ order.get_discount }}
                    </td>
                </tr>
                {% endif %}

                <tr class="total">
                    <td colspan="3">{% trans 'Total' %}</td>
                    <td class="num">{% trans '$' %}{{ order.get_total_price }}</td>
                </tr>
            </tbody>
        </table>

        <span class="{% if order.paid %}paid{% else %}pending{% endif %}">
            {% if order.is_paid %}
            {% trans 'Paid' %}
            {% else %}
            {% trans 'Pending payment' %}
            {% endif %}
        </span>
    </body>
</html>