config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = 'Store Management'
admin.site.index_title = 'Website Management'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('accounts/', include('store.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('', include('store.pages.urls', namespace='pages')),
    path('products/', include('store.products.urls', namespace='products')),
    path('comments/', include('store.comments.urls', namespace='comments')),
    path('qas/', include('store.qas.urls', namespace='qas')),
    path('cart/', include('store.cart.urls', namespace='cart')),
    path('search/', include('store.search.urls', namespace='search')),
    path('shipping/', include('store.shipping.urls', namespace='shipping')),
    path('orders/', include('store.orders.urls', namespace='orders')),
    path('coupons/', include('store.coupons.urls', namespace='coupons')),
    path('payment/', include('store.payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/shipping/urls.py
from django.urls import path

from . import views

app_name = 'shipping'

urlpatterns = [
    path('', views.shipping_create_view, name='create'),
    path('address/create/', views.AddressCreateView.as_view(), name='address_create'),
]

store/shipping/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from phonenumber_field.modelfields import PhoneNumberField


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_('user'))
    address = models.TextField(_('address'))
    city = models.CharField(_('city'), max_length=64)
    province = models.CharField(_('province'), max_length=64)
    building_number = models.PositiveSmallIntegerField(_('building_number'))
    unit = models.PositiveSmallIntegerField(_('unit'), blank=True, null=True)
    postal_code = models.CharField(_('postal_code'), max_length=10)
    receiver_first_name = models.CharField(_('receiver_first_name'), max_length=64)
    receiver_last_name = models.CharField(_('receiver_last_name'), max_length=64)
    mobile = PhoneNumberField(_('mobile'), region='IR')

    class Meta:
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')

    def __str__(self):
        return f'Address: {self.address}'


class TimeSlot(models.Model):
    start_time = models.TimeField(_('start_time'))
    end_time = models.TimeField(_('end_time'))

    class Meta:
        verbose_name = _('Time Slot')
        verbose_name_plural = _('Time Slots')

    def __str__(self):
        return f'{self.start_time} to {self.end_time}'


class Shipping(models.Model):
    address = models.ForeignKey('shipping.Address', on_delete=models.PROTECT, related_name='shippings', verbose_name=_('address'))
    delivery_date = models.DateField(_('delivery_date'))
    delivery_time_slot = models.ForeignKey('shipping.TimeSlot', on_delete=models.PROTECT, verbose_name=_('delivery_time_slot'))
    max_capacity = models.PositiveSmallIntegerField(_('max_capacity'), default=10)

    class Meta:
        verbose_name = _('Shipping')
        verbose_name_plural = _('Shippings')

    def __str__(self):
        return f'shipping id: {self.id} in {self.delivery_date}, {self.address.address}'

    def clean(self):
        if not self.time_slot_is_available():
            raise ValidationError('The selected time slot is not available.')

    def time_slot_is_available(self):
        existing_shipments = Shipping.objects.filter(
            delivery_date=self.delivery_date,
            delivery_time_slot=self.delivery_time_slot
        )
        return existing_shipments.count() < self.max_capacity

store/shipping/forms.py
from django import forms

from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget


from .models import Shipping, Address


class ShppingForm(forms.ModelForm):
    class Meta:
        model = Shipping
        fields = ('delivery_date', 'delivery_time_slot', 'address',)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['delivery_date'] = JalaliDateField(
            label='date',
            widget=AdminJalaliDateWidget()
        )
        self.fields['address'].queryset = Address.objects.filter(user=user)
        self.fields['address'].required = False


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('address', 'city', 'province', 'building_number',
                  'unit', 'postal_code', 'receiver_first_name',
                  'receiver_last_name', 'mobile',)

store/shipping/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils.translation import gettext as _

from store.cart.cart import Cart
from .forms import ShppingForm, AddressForm


@login_required
def shipping_create_view(request):
    cart = Cart(request)

    if len(cart) == 0:
        messages.warning(request, _('Your cart is empty please add product to cart.'))
        return redirect('products:list')

    if request.method == 'POST':
        shipping_form = ShppingForm(request.POST, user=request.user)
        address_form = AddressForm(request.POST)

        if shipping_form.is_valid():
            shipping_obj = shipping_form.save(commit=False)

            shipping_obj.save()

            request.session['shipping_id'] = shipping_obj.id

            messages.success(request, _('Your shipping successfully saved.'))

            return redirect('orders:create')

    else:
        shipping_form = ShppingForm(user=request.user)
        address_form = AddressForm()

    return render(request, 'shipping/create.html', {
        'shipping_form': shipping_form,
        'address_form': address_form,
    })


class AddressCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = AddressForm
    success_url = reverse_lazy('shipping:create')

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user

        messages.success(self.request, _('Your address successfully saved.'))

        return super().form_valid(form)

store/shipping/templates/shipping/create.html
{% extends '_base.html' %}

{% load static %}
{% load product_tags %}
{% load humanize %}
{% load i18n %}

{% load jalali_tags %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">

    <link href="{% static 'css/checkout.css' %}" rel="stylesheet">
{% endblock %}

{% block page_header %}
    {% trans 'Shipping Page' %}
{% endblock %}

{% block content %}
    <main class="bg_gray">
        <div class="container margin_30">
            <!-- /page_header -->
            {% if shipping_form.errors %}
                <div class="alert alert-danger">
                    {{ shipping_form.errors }}
                </div>
            {% endif %}
            {% if address_form.errors %}
                <div class="alert alert-danger">
                    {{ address_form.errors }}
                </div>
            {% endif %}
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="step first">
                        <h3>1. {% trans 'User Info and Billing address' %}</h3>
                        <ul class="nav nav-tabs" id="tab_checkout" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="#tab_1"
                                    role="tab" aria-controls="tab_1" aria-selected="true">{% trans 'Add New Address' %}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#tab_2" role="tab"
                                    aria-controls="tab_2" aria-selected="false">{% trans 'Choose A Address' %}</a>
                            </li>
                        </ul>
                        <form action="{% url 'shipping:address_create' %}" method="POST">
                            {% csrf_token %}
                            <div class="tab-content checkout">
                                <div class="tab-pane fade show active" id="tab_1" role="tabpanel"
                                    aria-labelledby="tab_1">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="{% trans 'First Name' %}"
                                            name="receiver_first_name">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="{% trans 'Last Name' %}"
                                            name="receiver_last_name">
                                    </div>
                                    <hr>
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="{% trans 'Full Address' %}"
                                            name="address">
                                    </div>
                                    <div class="row no-gutters">
                                        <div class="col-6 form-group pr-1">
                                            <input type="text" class="form-control" placeholder="{% trans 'City' %}" name="city">
                                        </div>
                                        <div class="col-6 form-group pr-1">
                                            <input type="text" class="form-control" placeholder="{% trans 'Province' %}"
                                                name="province">
                                        </div>
                                        <div class="col-6 form-group pr-1">
                                            <input type="text" class="form-control" placeholder="{% trans 'Building Number' %}"
                                                name="building_number">
                                        </div>
                                        <div class="col-6 form-group pr-1">
                                            <input type="text" class="form-control" placeholder="{% trans 'Unit' %}" name="unit">
                                        </div>
                                        <div class="col-6 form-group pl-1">
                                            <input type="text" class="form-control" placeholder="{% trans 'Postal code' %}"
                                                name="postal_code">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="{% trans 'Telephone' %}" name="mobile">
                                    </div>
                                    <hr>
                                    <div id="other_addr_c" class="pt-2">
                                        <div class="row no-gutters">
                                            <div class="col-6 form-group pr-1">
                                                <input type="text" class="form-control" placeholder="{% trans 'Name' %}">
                                            </div>
                                            <div class="col-6 form-group pl-1">
                                                <input type="text" class="form-control" placeholder="{% trans 'Last Name' %}">
                                            </div>
                                        </div>
                                        <!-- /row -->
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="{% trans 'Full Address' %}">
                                        </div>
                                        <div class="row no-gutters">
                                            <div class="col-6 form-group pr-1">
                                                <input type="text" class="form-control" placeholder="{% trans 'City' %}">
                                            </div>
                                            <div class="col-6 form-group pl-1">
                                                <input type="text" class="form-control" placeholder="{% trans 'Postal code' %}">
                                            </div>
                                        </div>
                                    </div>
                                    <input type="submit" class="btn_1 full-width" value="{% trans 'Save Address' %}">
                                </div>
                            </form>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="tab-pane fade" id="tab_2" role="tabpanel" aria-labelledby="tab_2"
                                    style="position: relative;">
                                    <div class="row no-gutters">
                                        <div class="col-md-12 form-group">
                                            <div class="custom-select-form">
                                                <select class="wide add_bottom_15" name="address" id="country">
                                                    {% for choice in shipping_form.address.field.queryset %}
                                                        <option value="{{ choice.pk }}">{{ choice }}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- /tab_2 -->
                            </div>
                        </div>
                    <!-- /step -->
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="step first">
                            <h3>2. {% trans 'Shipping' %}</h3>
                            <div class="tab-content checkout">
                                <div class="tab-pane fade show active" id="tab_1" role="tabpanel"
                                     aria-labelledby="tab_1">
                                    <div class="form-group">
                                        <input type="text" class="jalali_date-date form-control" placeholder="{% trans 'Calendar' %}"
                                               name="delivery_date">
                                    </div>
                                    <div class="row no-gutters">
                                        <div class="col-md-12 form-group">
                                            <div class="custom-select-form">
                                                <select class="wide add_bottom_15" name="delivery_time_slot"
                                                        id="country">
                                                    {% for choice in shipping_form.delivery_time_slot.field.queryset %}
                                                        <option value="{{ choice.pk }}">{{ choice }}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /step -->

                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="step last">
                            <h3>3. {% trans 'Order Summary' %}</h3>
                            <div class="box_general summary">

                                <ul>
                                    {% for item in cart %}
                                        <li class="clearfix"><em>{{ item.quantity }}x {{ item.product_obj.title }}</em>
                                            <span>{% trans '$' %}{{ item.price|persian_number|intcomma:False }}</span></li>
                                    {% endfor %}
                                </ul>

                                {% if cart.coupon %}
                                    
                                    <ul>
                                        <li class="clearfix">
                                            <em><strong>{% trans 'Subtotal' %}</strong></em>
                                            <span>{% trans '$' %}{{ cart.get_total_price|persian_number|intcomma:False }}</span>
                                        </li>
                                        
                                        <li class="clearfix">
                                            <em><strong>
                                                "{{ cart.coupon.code }}" {% trans 'coupon' %}
						                        ({{ cart.coupon.discount }}% {% trans 'off' %})
                                            </strong></em>
                                            <span>- {% trans '$' %}{{ cart.get_discount|persian_number|intcomma:False }}</span>
                                        </li>
                                    </ul>

                                {% endif %}


                                <div class="total clearfix">{% trans 'TOTAL' %} <span>{% trans '$' %}{{ cart.get_total_price_after_discount|persian_number|intcomma:False }}</span></div>

                                    <input type="submit" class="btn_1 full-width" value="{% trans 'Confirm' %}">
                                </div>
                                <!-- /box_general -->
                            </div>
                            <!-- /step -->
                        </div>
                    </div>
                    <!-- /row -->
                </form>
            </div>
            <!-- /container -->
        </main>
    <!--/main-->
{% endblock %}

{% block custom_js %}
    <script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
{% endblock %}