config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = 'Store Management'
admin.site.index_title = 'Website Management'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('accounts/', include('store.accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('', include('store.pages.urls', namespace='pages')),
    path('products/', include('store.products.urls', namespace='products')),
    path('comments/', include('store.comments.urls', namespace='comments')),
    path('qas/', include('store.qas.urls', namespace='qas')),
    path('cart/', include('store.cart.urls', namespace='cart')),
    path('search/', include('store.search.urls', namespace='search')),
    path('shipping/', include('store.shipping.urls', namespace='shipping')),
    path('orders/', include('store.orders.urls', namespace='orders')),
    path('coupons/', include('store.coupons.urls', namespace='coupons')),
    path('payment/', include('store.payment.urls', namespace='payment')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='add'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove'),
    path('clear/', views.cart_clear, name='clear'),
]

store/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('help/', views.HelpPageView.as_view(), name='help'),
]

store/products/urls.py
from django.urls import path, re_path

from . import views

app_name = 'products'

urlpatterns = [
    path('favorite/add/<int:product_id>/', views.product_favorite, name='add_favorite'),
    path('category/<slug:slug>/', views.CategoryListView.as_view(), name='category'),
    path('wishlist/', views.WishListView.as_view(), name='wish_list'),
    path('', views.ProductListView.as_view(), name='list'),
    re_path(r'(?P<slug>[-\w]+)/', views.ProductDetailView.as_view(), name='detail'),
]

store/qas/urls.py
from django.urls import path

from . import views

app_name = 'qas'

urlpatterns = [
    path('create/question/<int:product_id>/', views.QuestionCreateView.as_view(), name='question_create'),
    path('create/answer/<int:question_id>/', views.AnswerCreateView.as_view(), name='answer_create'),
]

store/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from phonenumber_field.modelfields import PhoneNumberField


class CustomUser(AbstractUser):
    phone_number = PhoneNumberField(_('phone_number'), unique=True, region='IR', null=True)


class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, primary_key=True, verbose_name=_('user'))
    birth_date = models.DateField(_('birth_date'), blank=True, null=True)

    class Meta:
        verbose_name = _('Customer')
        verbose_name_plural = _('Customers')

    def __str__(self):
        return f'{self.user.username}`s Profile'

    @property
    def age(self):
        if self.birth_date:
            today = timezone.now().today()
            age = today.year - self.birth_date.year - (
                    (today.month, today.day) < (self.birth_date.month, self.birth_date.day))
            return f'{age} yeas old'
        return

    @property
    def first_name(self):
        return self.user.first_name

    @property
    def last_name(self):
        return self.user.last_name

store/comments/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from django.conf import settings
from django.utils.translation import gettext_lazy as _


class Comment(models.Model):
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE, related_name='comments', verbose_name=_('product'))
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name='comments', verbose_name=_('author'))
    title = models.CharField(_('title'), max_length=256)
    body = models.TextField(_('body'), )
    is_active = models.BooleanField(_('is_active'), default=True)
    created = models.DateTimeField(_('created'), auto_now_add=True)
    modified = models.DateTimeField(_('modified'), auto_now=True)
    rate = models.IntegerField(_('rate'), default=1, validators=[MinValueValidator(1), MaxValueValidator(5)], blank=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='comment_likes', blank=True, verbose_name=_('likes'))
    dislikes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='comment_dislikes', blank=True, verbose_name=_('dislikes'))

    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

    def __str__(self):
        return f'{self.author} comment for {self.product}'

    @property
    def count_likes(self):
        return self.likes.count()

    @property
    def count_dislikes(self):
        return self.dislikes.count()

    def get_absolute_url(self):
        return reverse('products:detail', args=[self.product.slug])

store/payment/models.py
from django.db import models

# Create your models here.

store/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django import forms
from django.utils.translation import gettext_lazy as _

from allauth.account.forms import SignupForm as AllAuthSignupForm
from phonenumber_field.formfields import PhoneNumberField
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget

from store.accounts.models import Customer

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'username',)


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'username',)


class CustomSignupForm(AllAuthSignupForm):
    phone_number = PhoneNumberField(region='IR', label=_('Your Phone Number'))

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']
        if not User.objects.filter(phone_number=data).exists():
            return data
        raise forms.ValidationError(_('User with this phone number already exists.'))

    def save(self, request):
        user = super().save(request)
        user.phone_number = self.cleaned_data['phone_number']
        user.save()
        return user


class PhoneNumberForm(forms.Form):
    phone_number = PhoneNumberField(region='IR', label=_('Your Phone Number'))


class VerifyForm(forms.Form):
    code = forms.CharField(max_length=5, label=_('code'))


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name',)


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('birth_date',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['birth_date'] = JalaliDateField(
            label='date',
            widget=AdminJalaliDateWidget()
        )

store/cart/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label=_('quantity')
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput,
    )

store/comments/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('title', 'body', 'rate',)

store/coupons/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class CouponApplyForm(forms.Form):
    code = forms.CharField(label=_('code'))
    

store/orders/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('note',)

store/products/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class SortForm(forms.Form):
    SORT_CHOICES = (
        ('sale_price', _('Sort by price: low to high')),
        ('-sale_price', _('Sort by price: high to low')),
        ('-created', _('Sort by new')),
    )

    field = forms.ChoiceField(choices=SORT_CHOICES, label=_('field'))

store/qas/forms.py
from django import forms

from .models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text',)


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('text',)

store/shipping/forms.py
from django import forms

from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget


from .models import Shipping, Address


class ShppingForm(forms.ModelForm):
    class Meta:
        model = Shipping
        fields = ('delivery_date', 'delivery_time_slot', 'address',)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['delivery_date'] = JalaliDateField(
            label='date',
            widget=AdminJalaliDateWidget()
        )
        self.fields['address'].queryset = Address.objects.filter(user=user)
        self.fields['address'].required = False


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('address', 'city', 'province', 'building_number',
                  'unit', 'postal_code', 'receiver_first_name',
                  'receiver_last_name', 'mobile',)

store/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.utils.translation import gettext as _

from allauth.account.views import PasswordChangeView as AllAuthPasswordChangeView

from .forms import PhoneNumberForm, VerifyForm, ProfileUpdateForm, UserUpdateForm
from .utils import generate_random_otp, verify_otp_code, store_otp_in_cache
from .decorators import unauthenticated_required

User = get_user_model()


@unauthenticated_required
def send_otp(request):
    if request.method == 'POST':
        form = PhoneNumberForm(request.POST)
        if form.is_valid():
            phone_number = form.cleaned_data['phone_number']
            if User.objects.filter(phone_number=phone_number).exists():
                otp_code = generate_random_otp()
                store_otp_in_cache(phone_number, otp_code)
                request.session['phone_number'] = str(phone_number)
                print(otp_code)
                messages.success(request, _('Code sent successfully'))
                return redirect('accounts:verify_otp')
            else:
                messages.error(request, _('User with this phone number does not exists.'))
    else:
        form = PhoneNumberForm()

    return render(request, 'account/login_otp.html', {'form': form})


def verify_otp(request):
    phone_number = request.session.get('phone_number')

    if not phone_number:
        return redirect('accounts:send_otp')

    if request.method == 'POST':
        form = VerifyForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            if verify_otp_code(code, phone_number):
                user = authenticate(request, username=phone_number)
                if user is not None:
                    login(request, user)
                    del request.session['phone_number']
                    messages.success(request, _('Authentication successfully.'))
                    return redirect('pages:home')
                else:
                    messages.error(request, _('Authentication faild.'))
            else:
                messages.error(request, _('Invalid OTP code.'))

    else:
        form = VerifyForm()

    return render(request, 'account/verify_otp.html', {'form': form})


class CustomPasswordChangeView(AllAuthPasswordChangeView):
    success_url = reverse_lazy('pages:home')


@login_required
def profile(request):

    if request.method == 'POST':
        user_form = UserUpdateForm(
            request.POST,
            instance=request.user
        )
        profile_form = ProfileUpdateForm(
            request.POST,
            instance=request.user.customer
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Your account has been updated.'))
            return redirect('accounts:profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.customer)

    return render(request, 'accounts/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })

store/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.utils.translation import gettext as _
from django.contrib import messages

from store.products.models import Product
from store.coupons.forms import CouponApplyForm
from .cart import Cart
from .forms import CartAddProductForm


def cart_detail(request):
    cart = Cart(request)

    for item in cart:
        item['product_update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'override': True
            }
        )

    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {
        'cart': cart, 
        'coupon_apply_form': coupon_apply_form,
    })


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product, cd['quantity'], cd['override'])

    return redirect('cart:detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def cart_clear(request):
    cart = Cart(request)

    if len(cart):
        cart.clear()
        messages.success(request, _('All products successfully removed from your cart'))
    else:
        messages.warning(request, _('Your cart is already empty.'))

    return redirect('cart:detail')

store/comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.translation import gettext as _

from .forms import CommentForm
from .models import Comment
from store.products.models import Product


class CommentCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = CommentForm
    template_name = 'comments/comment_form.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user

        product_id = self.kwargs.get('product_id')
        product = get_object_or_404(Product, pk=product_id)
        obj.product = product

        messages.success(self.request, _('Comment successfully saved.'))

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        product_id = self.kwargs.get('product_id')
        product = get_object_or_404(Product, pk=product_id)
        
        context['product'] = product
        return context


@login_required
def comment_like(request, comment_id, reaction):
    comment = get_object_or_404(Comment, pk=comment_id)

    if reaction == 'like':
        reaction_set = comment.likes
        other_reaction_set = comment.dislikes
    elif reaction == 'dislike':
        reaction_set = comment.dislikes
        other_reaction_set = comment.likes
    else:
        return redirect(comment.get_absolute_url())

    if request.user in reaction_set.all():
        reaction_set.remove(request.user)
        messages.success(request, _('Your like successfully saved.'))
    elif request.user in other_reaction_set.all():
        reaction_set.add(request.user)
        other_reaction_set.remove(request.user)
        messages.success(request, _('Your dislike successfully saved.'))
    else:
        reaction_set.add(request.user)
        messages.success(request, _('Your like successfully saved.'))

    return redirect(comment.get_absolute_url())

store/templates/help.html
{% extends '_base.html' %}

{% load static %}

{% block page_title %}
    Help Page
{% endblock %}

{% block custom_css %}
    <!-- SPECIFIC CSS -->
    <link href="{% static 'css/faq.css' %}" rel="stylesheet">
{% endblock %}
    
{% block content %}
<main class="bg_gray">
	
		
	
		
		<div class="bg_white">
			<div class="container margin_90_65">
				<div class="main_title">
					<h2>Our Support Sections</h2>
					<p>Read articles and questions</p>
				</div>
				
				<div class="row">
					<div class="col-md-6">
						<a class="box_topic_2" href="">
						<i class="ti-wallet"></i>
						<h3>Payments</h3>
						<p>Eu qui mundi lucilius petentium, mea amet libris prodesset in, ei unum delectus vituperata eum. Ne usu omittam menandri.</p>
					</a>
					</div>
					<div class="col-md-6">
						<a class="box_topic_2" href="">
						<i class="ti-user"></i>
						<h3>Account</h3>
						<p>Eu qui mundi lucilius petentium, mea amet libris prodesset in, ei unum delectus vituperata eum. Ne usu omittam menandri.</p>
					</a>
					</div>
				</div>
				<!-- /row -->
				
				<div class="row">
					<div class="col-md-6">
						<a class="box_topic_2" href="">
						<i class="ti-help"></i>
						<h3>General help</h3>
						<p>Eu qui mundi lucilius petentium, mea amet libris prodesset in, ei unum delectus vituperata eum. Ne usu omittam menandri.</p>
					</a>
					</div>
					<div class="col-md-6">
						<a class="box_topic_2" href="">
						<i class="ti-truck"></i>
						<h3>Shipping</h3>
						<p>Eu qui mundi lucilius petentium, mea amet libris prodesset in, ei unum delectus vituperata eum. Ne usu omittam menandri.</p>
					</a>
					</div>
				</div>
				<!-- /row -->
				
				<div class="row">
					<div class="col-md-6">
						<a class="box_topic_2" href="">
						<i class="ti-eraser"></i>
						<h3>Refunds</h3>
						<p>Eu qui mundi lucilius petentium, mea amet libris prodesset in, ei unum delectus vituperata eum. Ne usu omittam menandri.</p>
					</a>
					</div>
					<div class="col-md-6">
						<a class="box_topic_2" href="">
						<i class="ti-comments"></i>
						<h3>Reviews</h3>
						<p>Eu qui mundi lucilius petentium, mea amet libris prodesset in, ei unum delectus vituperata eum. Ne usu omittam menandri.</p>
					</a>
					</div>
				</div>
				<!-- /row -->					
			</div>
			<!-- /container -->	
		</div>
		<!-- /bg_white -->
	</main>
	<!--/main-->
{% endblock %}

store/templates/home.html
{% extends '_base.html' %}

{% load static %}
{% load product_tags %}
{% load humanize %}
{% load i18n %}

{% block page_title %}
Home Page
{% endblock %}

{% block content %}
<main>
	<div id="carousel-home">
		<div class="owl-carousel owl-theme">
			<div class="owl-slide cover"
				style="background-image: url({% static 'img/slides/banner-skinnova-phone-category.webp' %});">
				<div class="opacity-mask d-flex align-items-center"
					data-opacity-mask="rgba(0, 0, 0, 0.5)">
					<div class="container">
						<div class="row justify-content-center justify-content-md-end">
							<div class="col-lg-6 static">
								<div class="slide-text text-end white">
									<h2 class="owl-slide-animated owl-slide-title">{% trans 'New mobile' %}</h2><br>
									<div class="owl-slide-animated owl-slide-cta"><a class="btn_1"
											href="{% url 'products:category' 'mobile' %}" role="button">{% trans 'Shop Now' %}</a></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--/owl-slide-->
			<div class="owl-slide cover"
				style="background-image: url({% static 'img/slides/laptop-Featured-Image.jpg' %});">
				<div class="opacity-mask d-flex align-items-center"
					data-opacity-mask="rgba(0, 0, 0, 0.5)">
					<div class="container">
						<div class="row justify-content-center justify-content-md-start">
							<div class="col-lg-6 static">
								<div class="slide-text white">
									<h2 class="owl-slide-animated owl-slide-title">{% trans 'New laptop' %}</h2><br>
									<div class="owl-slide-animated owl-slide-cta"><a class="btn_1"
											href="{% url 'products:category' 'laptop' %}" role="button">{% trans 'Shop Now' %}</a></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!--/owl-slide-->
			<div class="owl-slide cover"
				style="background-image: url({% static 'img/slides/headphone-price-category-banner-01.jpg' %});">
				<div class="opacity-mask d-flex align-items-center"
					data-opacity-mask="rgba(0, 0, 0, 0.5)">
					<div class="container">
						<div class="row justify-content-center justify-content-md-start">
							<div class="col-lg-12 static">
								<div class="slide-text text-center white">
									<h2 class="owl-slide-animated owl-slide-title">{% trans 'New headphones' %}</h2><br>
									<div class="owl-slide-animated owl-slide-cta"><a class="btn_1"
											href="{% url 'products:category' 'headphone' %}" role="button">{% trans 'Shop Now' %}</a></div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--/owl-slide-->
			</div>
		</div>
		<div id="icon_drag_mobile"></div>
	</div>
	<!--/carousel-->

	<ul id="banners_grid" class="clearfix">
		<li>
			<a href="{% url 'products:category' 'men' %}" class="img_container">
				<img src="{% static 'img/banners_cat_placeholder.jpg' %}"
					data-src="{% static 'img/istockphoto-665032164-612x612.jpg' %}" alt
					class="lazy">
				<div class="short_info opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.5)">
					<h3>{% trans "Men's Collection" %}</h3>
					<div><span class="btn_1">{% trans 'Shop Now' %}</span></div>
				</div>
			</a>
		</li>
		<li>
			<a href="{% url 'products:category' 'women' %}" class="img_container">
				<img src="{% static 'img/banners_cat_placeholder.jpg' %}"
					data-src="{% static 'img/DKNY_SITE_CATEGORY_BANNERS_Women.webp' %}" alt
					class="lazy">
				<div class="short_info opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.5)">
					<h3>{% trans "Womens's Collection" %}</h3>
					<div><span class="btn_1">{% trans 'Shop Now' %}</span></div>
				</div>
			</a>
		</li>
		<li>
			<a href="{% url 'products:category' 'kid' %}" class="img_container">
				<img src="{% static 'img/banners_cat_placeholder.jpg' %}"
					data-src="{% static 'img/SU235172_GapBaby_img_MOB.webp' %}" alt class="lazy">
				<div class="short_info opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.5)">
					<h3>{% trans "Kids's Collection" %}</h3>
					<div><span class="btn_1">{% trans 'Shop Now' %}</span></div>
				</div>
			</a>
		</li>
	</ul>
	<!--/banners_grid -->

	<div class="container margin_60_35">
		<div class="main_title">
			<h2>{% trans 'Top Selling' %}</h2>
			<span>{% trans 'Products' %}</span>
		</div>
		<div class="row small-gutters">

			{% with most_sold_products as products %}
			{% for product in products %}

			<div class="col-6 col-md-4 col-xl-3">
				<div class="grid_item">
					<figure>
						{% if product.discount %}
						<span class="ribbon off">-{{ product.discount }}%</span>
						{% endif %}
						<a href="{{ product.get_absolute_url }}">
							<img class="img-fluid lazy" data-src="{{ product.main_cover.url }}" alt>
						</a>
					</figure>
					{% if product.num_stock <= product.threshold_low_stock %}
					<p class="text-danger">{{ product.num_stock }} {% trans 'in stock' %}</p>
					{% endif %}
					<a href="{{ product.get_absolute_url }}">
						<h3>{{ product.title }}</h3>
					</a>
					<div class="price_box">
						{% if product.discount %}
						<span class="new_price">{% trans '$' %}{{ product.final_price|persian_number|intcomma:False }}</span>
						<span class="old_price">{% trans '$' %}{{ product.sale_price|persian_number|intcomma:False }}</span>
						{% else %}
						<span class="new_price">{% trans '$' %}{{ product.sale_price|persian_number|intcomma:False }}</span>
						{% endif %}
					</div>
					<div class="price_box">
						<form action="{% url 'cart:add' product.id %}" method="POST">
							{% csrf_token %}
							<input type="submit" class="btn btn-primary btn-sm" value="{% trans 'Add To Cart' %}">
							<input type="hidden" name="quantity" value="1">
						</form>
					</div>
				</div>
				<!-- /grid_item -->
			</div>
			<!-- /col -->

			{% endfor %}
			{% endwith %}

		</div>
		<!-- /row -->
	</div>
	<!-- /container -->

	<div class="container margin_60_35">
		<div class="main_title">
			<h2>{% trans 'Top Hits' %}</h2>
			<span>{% trans 'Products' %}</span>
		</div>
		<div class="owl-carousel owl-theme products_carousel">
			{% with most_hits_products as products %}
			{% for product in products %}
			<div class="item">
				<div class="grid_item">
					{% if product.discount %}
					<span class="ribbon off">-{{ product.discount }}%</span>
					{% endif %}
					<figure>
						<a href="{{ product.get_absolute_url }}">
							<img class="owl-lazy" data-src="{{ product.main_cover.url }}" alt>
						</a>
					</figure>
					{% if product.num_stock <= product.threshold_low_stock %}
					<p class="text-danger">{{ product.num_stock }} {% trans 'in stock' %}</p>
					{% endif %}
					<a href="{{ product.get_absolute_url }}">
						<h3>{{ product.title }}</h3>
					</a>
					{% if product.num_stock %}
					<div class="price_box">
						{% if product.discount %}
						<span class="new_price">{% trans '$' %}{{ product.final_price|persian_number|intcomma:False }}</span>
						<span class="old_price">{% trans '$' %}{{ product.sale_price|persian_number|intcomma:False }}</span>
						{% else %}
						<span class="new_price">{% trans '$' %}{{ product.sale_price|persian_number|intcomma:False }}</span>
						{% endif %}
					</div>
					<div class="price_box">
						<form action="{% url 'cart:add' product.id %}" method="POST">
							{% csrf_token %}
							<input type="submit" class="btn btn-primary btn-sm" value="{% trans 'Add To Cart' %}">
							<input type="hidden" name="quantity" value="1">
						</form>
					</div>
					{% else %}
					<div class="price_box">
						<span class="new_price">{% trans 'Unavailable' %}</span>
					</div>
					{% endif %}
				</div>
				<!-- /grid_item -->
			</div>
			<!-- /item -->
			{% endfor %}
			{% endwith %}
		</div>
		<!-- /products_carousel -->
	</div>
	<!-- /container -->
</main>
<!-- /main -->

{% endblock %}